apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-monitoring
  name: cluster-monitoring-config
data:
  'config.yaml': |
    enableUserWorkload: true
    prometheusK8s:
      retention: 3d
