apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

resources:
  - github.com/metallb/metallb/manifests?ref=0.12.1
  - configuration.yaml

patches:
# This patch removes the hardcoded non-root user metallb carries by default
# since Openshift will automatically assign a non-root user for the containers.
  - target:
      kind: Deployment
      name: controller
    path: remove_hardcoded_user.json
