---
- hosts: all
  become: true
  tasks:
    - name: Copy isos
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/var/lib/libvirt/images/{{ item }}"
        mode: '0644'
      with_items:
        - worker.iso
        - master.iso
        - bootstrap.iso
